using MicroCMS.Application.Common.Interfaces;
using MicroCMS.Application.Features.Delivery.Dtos;
using MicroCMS.Application.Features.Delivery.Queries;
using MicroCMS.Delivery.Core.Extensions;
using MicroCMS.Domain.Aggregates.Media;
using MicroCMS.Domain.Enums;
using MicroCMS.Domain.Repositories;
using MicroCMS.Domain.Services;
using MicroCMS.Domain.Specifications.Delivery;
using MicroCMS.Shared.Ids;
using MicroCMS.Shared.Primitives;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MicroCMS.Delivery.WebHost.Controllers;

/// <summary>
/// Delivery API — available media assets.
///
/// Three surfaces:
/// <list type="bullet">
///   <item><description><c>GET /delivery/v1/media</c> — paginated list with resolved URLs.</description></item>
///   <item><description><c>GET /delivery/v1/media/{id}</c> — single asset metadata + resolved URL.</description></item>
///   <item><description><c>GET /delivery/v1/media/{id}/stream</c> — binary stream passthrough
///     (used when the storage provider does not expose a public URL, e.g. Filesystem dev mode).
///     Private assets are validated via signed-URL query params before streaming.</description></item>
/// </list>
///
/// Only <b>Available</b> assets are exposed; uploading / quarantined / deleted assets return 404.
/// </summary>
[Authorize(Policy = DeliveryPolicies.ApiKeyAuthenticated)]
public sealed class MediaController : DeliveryControllerBase
{
    /// <summary>
    /// Lists available media assets for a site, with resolved public or signed URLs.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedList<DeliveryMediaAssetDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> List(
     [FromQuery] Guid siteId,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 50,
        CancellationToken cancellationToken = default)
    {
    pageSize = Math.Clamp(pageSize, 1, 200);
   var result = await Sender.Send(
      new ListDeliveryMediaAssetsQuery(siteId, page, pageSize),
            cancellationToken);
        return OkOrProblem(result);
    }

    /// <summary>
    /// Returns metadata and a resolved URL for a single available media asset.
    /// </summary>
    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(DeliveryMediaAssetDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Get(
[FromQuery] Guid siteId,
      Guid id,
      CancellationToken cancellationToken = default)
    {
     var result = await Sender.Send(
  new GetDeliveryMediaAssetQuery(siteId, id),
    cancellationToken);
        return OkOrProblem(result);
  }

    /// <summary>
    /// Streams the raw binary content of a media asset directly from storage.
    ///
    /// <b>Public assets</b>: requires only a valid <c>X-Api-Key</c> header.
    /// <b>Private assets</b>: additionally requires <c>exp</c>, <c>tid</c>, and <c>sig</c>
    ///   query parameters generated by the signed-URL service; the HMAC is validated
    ///   before the stream is opened.
    /// </summary>
    /// <param name="siteId">Site GUID — prevents cross-site asset access.</param>
    /// <param name="id">Asset ID.</param>
    /// <param name="exp">Unix timestamp expiry (required for private assets).</param>
    /// <param name="tid">Tenant ID embedded in the signature (required for private assets).</param>
    /// <param name="sig">HMAC-SHA256 signature (required for private assets).</param>
    [HttpGet("{id:guid}/stream")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Stream(
        [FromQuery] Guid siteId,
        Guid id,
   [FromQuery] long? exp = null,
   [FromQuery] string? tid = null,
        [FromQuery] string? sig = null,
        CancellationToken cancellationToken = default)
    {
        // Resolve the asset directly — no MediatR round-trip needed for streaming.
var assetRepo = HttpContext.RequestServices
     .GetRequiredService<IRepository<MediaAsset, MediaAssetId>>();
        var storage   = HttpContext.RequestServices
         .GetRequiredService<IStorageProvider>();
        var signer    = HttpContext.RequestServices
 .GetRequiredService<IStorageSigningService>();

        var matches = await assetRepo.ListAsync(
      new AvailableMediaAssetByIdSpec(new MediaAssetId(id)),
            cancellationToken);

      var asset = matches.FirstOrDefault(a => a.SiteId == new SiteId(siteId));
        if (asset is null)
         return NotFound();

      // ── Private asset: validate signed-URL params ─────────────────────
        if (asset.Visibility == AssetVisibility.Private)
        {
            if (exp is null || tid is null || sig is null)
                return Forbid();

   if (!signer.Validate(asset.StorageKey, exp.Value, tid, sig))
            return Forbid();
     }

        // ── Stream from storage ───────────────────────────────────────────
     var stream = await storage.DownloadAsync(asset.StorageKey, cancellationToken);
        return File(stream, asset.Metadata.MimeType, asset.Metadata.FileName, enableRangeProcessing: true);
    }
}
