using MediatR;
using MicroCMS.Application.Common.Attributes;
using MicroCMS.Application.Common.Authorization;
using MicroCMS.Application.Common.Exceptions;
using MicroCMS.Application.Common.Interfaces;
using MicroCMS.Application.Common.Markers;
using MicroCMS.Domain.Aggregates.Webhooks;
using MicroCMS.Domain.Repositories;
using MicroCMS.Shared.Ids;
using MicroCMS.Shared.Results;

namespace MicroCMS.Application.Features.Webhooks.Commands;

// ── DTO ───────────────────────────────────────────────────────────────────────

public sealed record WebhookSubscriptionDto(
    Guid Id,
    string TargetUrl,
    bool IsActive,
    IReadOnlyList<string> Events,
    int MaxRetries,
    Guid? SiteId);

// ── Commands ──────────────────────────────────────────────────────────────────

/// <summary>
/// Creates a new webhook subscription (GAP-19).
/// Returns the hashed secret — the raw key is generated by the caller and shown once.
/// </summary>
[HasPolicy(ContentPolicies.TenantManage)]
public sealed record CreateWebhookCommand(
    Guid? SiteId,
  string TargetUrl,
    string HashedSecret,
    IReadOnlyList<string> Events,
    int MaxRetries = 3) : ICommand<WebhookSubscriptionDto>;

/// <summary>Updates the event list and active state of a webhook subscription (GAP-19).</summary>
[HasPolicy(ContentPolicies.TenantManage)]
public sealed record UpdateWebhookCommand(
    Guid SubscriptionId,
    IReadOnlyList<string> Events,
    bool IsActive) : ICommand<WebhookSubscriptionDto>;

/// <summary>Permanently deletes a webhook subscription (GAP-19).</summary>
[HasPolicy(ContentPolicies.TenantManage)]
public sealed record DeleteWebhookCommand(Guid SubscriptionId) : ICommand;

// ── Handlers ──────────────────────────────────────────────────────────────────

internal sealed class CreateWebhookCommandHandler(
    IRepository<WebhookSubscription, WebhookSubscriptionId> webhookRepository,
    ICurrentUser currentUser)
    : IRequestHandler<CreateWebhookCommand, Result<WebhookSubscriptionDto>>
{
    public async Task<Result<WebhookSubscriptionDto>> Handle(
       CreateWebhookCommand request, CancellationToken cancellationToken)
    {
      var siteId = request.SiteId.HasValue ? new SiteId(request.SiteId.Value) : (SiteId?)null;
      var sub = WebhookSubscription.Create(
  currentUser.TenantId, siteId,
   request.TargetUrl, request.HashedSecret,
 request.Events, request.MaxRetries);
  await webhookRepository.AddAsync(sub, cancellationToken);
     return Result.Success(WebhookMapper.ToDto(sub));
    }
}

internal sealed class UpdateWebhookCommandHandler(
    IRepository<WebhookSubscription, WebhookSubscriptionId> webhookRepository)
    : IRequestHandler<UpdateWebhookCommand, Result<WebhookSubscriptionDto>>
{
    public async Task<Result<WebhookSubscriptionDto>> Handle(
  UpdateWebhookCommand request, CancellationToken cancellationToken)
    {
     var id = new WebhookSubscriptionId(request.SubscriptionId);
    var sub = await webhookRepository.GetByIdAsync(id, cancellationToken)
  ?? throw new NotFoundException(nameof(WebhookSubscription), request.SubscriptionId);
   sub.UpdateEvents(request.Events);
   if (request.IsActive) sub.Activate(); else sub.Deactivate();
    webhookRepository.Update(sub);
  return Result.Success(WebhookMapper.ToDto(sub));
    }
}

internal sealed class DeleteWebhookCommandHandler(
  IRepository<WebhookSubscription, WebhookSubscriptionId> webhookRepository)
    : IRequestHandler<DeleteWebhookCommand, Result>
{
    public async Task<Result> Handle(DeleteWebhookCommand request, CancellationToken cancellationToken)
    {
    var id = new WebhookSubscriptionId(request.SubscriptionId);
  var sub = await webhookRepository.GetByIdAsync(id, cancellationToken)
   ?? throw new NotFoundException(nameof(WebhookSubscription), request.SubscriptionId);
  webhookRepository.Remove(sub);
     return Result.Success();
    }
}

internal static class WebhookMapper
{
    internal static WebhookSubscriptionDto ToDto(WebhookSubscription s) => new(
  s.Id.Value, s.TargetUrl, s.IsActive, s.Events, s.MaxRetries, s.SiteId?.Value);
}
