// <auto-generated />
using System;
using MicroCMS.Infrastructure.Persistence.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroCMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Ai.AiProviderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("AiProviderSettings", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Ai.CopilotConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GroundedOnlyMode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastMessageAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("TotalPromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CopilotConversations", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BackingContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZonesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.ComponentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedOnPages")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "Status");

                    b.ToTable("ComponentItems", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultPlacementsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShellTemplate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZonesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Key")
                        .IsUnique();

                    b.ToTable("Layouts", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.PageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacementsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PageTemplates", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.SiteTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SiteId");

                    b.ToTable("SiteTemplates", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Content.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Content");

                    b.Property<Guid?>("LayoutId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizationMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PerLocale");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Handle")
                        .IsUnique();

                    b.ToTable("ContentTypes", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Content.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledPublishAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledUnpublishAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Locale", "Slug")
                        .IsUnique();

                    b.ToTable("Entries", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Content.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SiteId", "ParentFolderId");

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Identity.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AttemptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("TenantId", "Email", "AttemptedAt");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PasswordChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(72)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Locks.EditLock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LockedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LockedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("EditLocks", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Media.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiAltText")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Media.MediaFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SiteId", "ParentFolderId");

                    b.ToTable("MediaFolders", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Pages.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CollectionContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LayoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutePattern")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "ParentId");

                    b.HasIndex("SiteId", "Slug")
                        .IsUnique();

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Plugins.Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("InstalledAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("_capabilities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Capabilities");

                    b.HasKey("Id");

                    b.ToTable("Plugins", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Settings.TenantConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TenantConfigs", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Taxonomy.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Taxonomy.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Tenant.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("_scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Scopes");

                    b.HasKey("Id");

                    b.ToTable("ApiClients", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Tenant.SiteSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreviewEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewUrlTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SchedulingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VersioningEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WorkflowEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_corsOrigins")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("CorsOrigins");

                    b.Property<string>("_locales")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Locales");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Tenant.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Tenant.TenantSecuritySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AbsoluteSessionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OidcIssuer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireMfaForAdmins")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionIdleTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SsoEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_ipAllowlist")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("IpAllowlist");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSecuritySettings", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Webhooks.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("_events")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Events");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptions", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Infrastructure.Persistence.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredOnUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedOnUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.HasIndex("TenantId", "ProcessedOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Ai.AiProviderSettings", b =>
                {
                    b.OwnsOne("MicroCMS.Domain.Aggregates.Ai.AiBudget", "Budget", b1 =>
                        {
                            b1.Property<Guid>("AiProviderSettingsId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CurrentMonthSpendUsd")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Budget_CurrentMonthSpendUsd");

                            b1.Property<bool>("HardStop")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Budget_HardStop");

                            b1.Property<decimal>("MonthlyCostCapUsd")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Budget_MonthlyCostCapUsd");

                            b1.Property<int>("PerUserDailyTokenCap")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Budget_PerUserDailyTokenCap");

                            b1.HasKey("AiProviderSettingsId");

                            b1.ToTable("AiProviderSettings");

                            b1.WithOwner()
                                .HasForeignKey("AiProviderSettingsId");
                        });

                    b.OwnsMany("MicroCMS.Domain.Aggregates.Ai.AiModelTierOverride", "ModelOverrides", b1 =>
                        {
                            b1.Property<Guid>("AiProviderSettingsId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FeatureKey")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("AiProviderSettingsId", "FeatureKey");

                            b1.ToTable("AiModelTierOverrides", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AiProviderSettingsId");
                        });

                    b.OwnsOne("MicroCMS.Domain.Aggregates.Ai.AiSafetyConfig", "Safety", b1 =>
                        {
                            b1.Property<Guid>("AiProviderSettingsId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AuditLogRetentionDays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Safety_AuditLogRetentionDays");

                            b1.Property<string>("DataResidencyRegion")
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("Safety_DataResidencyRegion");

                            b1.Property<bool>("GroundedOnlyModeDefault")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Safety_GroundedOnlyModeDefault");

                            b1.Property<bool>("PiiRedactionEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Safety_PiiRedactionEnabled");

                            b1.Property<bool>("PromptInjectionDetectionEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Safety_PromptInjectionDetectionEnabled");

                            b1.Property<bool>("SafetyPostFilterEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Safety_SafetyPostFilterEnabled");

                            b1.HasKey("AiProviderSettingsId");

                            b1.ToTable("AiProviderSettings");

                            b1.WithOwner()
                                .HasForeignKey("AiProviderSettingsId");
                        });

                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("ModelOverrides");

                    b.Navigation("Safety")
                        .IsRequired();
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Ai.CopilotConversation", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Ai.CopilotMessage", "Messages", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ConversationId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ConversationId");

                            b1.ToTable("CopilotMessages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");

                            b1.OwnsMany("MicroCMS.Domain.Aggregates.Ai.CopilotCitation", "Citations", b2 =>
                                {
                                    b2.Property<Guid>("MessageId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("EntryId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("SimilarityScore")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("Slug")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MessageId", "EntryId");

                                    b2.ToTable("CopilotMessageCitations", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MessageId");
                                });

                            b1.Navigation("Citations");
                        });

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.Component", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Content.FieldDefinition", "Fields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ComponentId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ContentTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FieldType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Handle")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsIndexed")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsList")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false);

                            b1.Property<bool>("IsLocalized")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsUnique")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ValidationJson")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ComponentId");

                            b1.ToTable("ComponentFields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ComponentId");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Components.PageTemplate", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Components.ComponentPlacement", "Placements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("BoundItemId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ComponentId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsLayoutDefault")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false);

                            b1.Property<Guid>("PageTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Zone")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("PageTemplateId");

                            b1.ToTable("PageTemplatePlacements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PageTemplateId");
                        });

                    b.Navigation("Placements");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Content.ContentType", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Content.FieldDefinition", "Fields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ContentTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FieldType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Handle")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsIndexed")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsList")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false);

                            b1.Property<bool>("IsLocalized")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsUnique")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ValidationJson")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ContentTypeId", "Handle")
                                .IsUnique();

                            b1.ToTable("ContentTypeFields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContentTypeId");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Content.Entry", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Content.EntryVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ChangeNote")
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("EntryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FieldsJson")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("EntryId");

                            b1.ToTable("EntryVersions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EntryId");
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Identity.User", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Identity.Role", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("SiteId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkflowRole")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Media.MediaAsset", b =>
                {
                    b.OwnsOne("MicroCMS.Domain.ValueObjects.AssetMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan?>("Duration")
                                .HasColumnType("TEXT")
                                .HasColumnName("Meta_Duration");

                            b1.Property<string>("ExifData")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Meta_ExifJson");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Meta_FileName");

                            b1.Property<int?>("HeightPx")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Meta_HeightPx");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(127)
                                .HasColumnType("TEXT")
                                .HasColumnName("Meta_MimeType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Meta_SizeBytes");

                            b1.Property<int?>("WidthPx")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Meta_WidthPx");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("MediaAssets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Pages.Page", b =>
                {
                    b.OwnsOne("MicroCMS.Domain.ValueObjects.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("PageId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CanonicalUrl")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("SeoCanonicalUrl");

                            b1.Property<string>("MetaDescription")
                                .HasMaxLength(160)
                                .HasColumnType("TEXT")
                                .HasColumnName("SeoMetaDescription");

                            b1.Property<string>("MetaTitle")
                                .HasMaxLength(60)
                                .HasColumnType("TEXT")
                                .HasColumnName("SeoMetaTitle");

                            b1.Property<string>("OgImage")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("SeoOgImage");

                            b1.HasKey("PageId");

                            b1.ToTable("Pages");

                            b1.WithOwner()
                                .HasForeignKey("PageId");
                        });

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Settings.TenantConfig", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Settings.ConfigEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("general");

                            b1.Property<bool>("IsSecret")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TenantConfigId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("UpdatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantConfigId", "Key")
                                .IsUnique();

                            b1.ToTable("TenantConfigEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantConfigId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Tenant.SiteSettings", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Settings.ConfigEntry", "ConfigEntries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("general");

                            b1.Property<bool>("IsSecret")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SiteSettingsId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("UpdatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SiteSettingsId", "Key")
                                .IsUnique();

                            b1.ToTable("SiteConfigEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SiteSettingsId");
                        });

                    b.Navigation("ConfigEntries");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Tenant.Tenant", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Tenant.Site", "Sites", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CustomDomain")
                                .HasMaxLength(253)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DefaultLocale")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Handle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId", "Handle")
                                .IsUnique();

                            b1.ToTable("Sites", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsMany("MicroCMS.Domain.ValueObjects.SiteEnvironment", "Environments", b2 =>
                                {
                                    b2.Property<Guid>("SiteId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(32)
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("IsLive")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("SslStatus")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("SiteId", "Type");

                                    b2.ToTable("SiteEnvironments", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SiteId");
                                });

                            b1.Navigation("Environments");
                        });

                    b.OwnsOne("MicroCMS.Domain.ValueObjects.TenantQuota", "Quota", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("MaxAiTokensPerMonth")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quota_MaxAiTokensPerMonth");

                            b1.Property<int>("MaxApiCallsPerMinute")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quota_MaxApiCallsPerMinute");

                            b1.Property<int>("MaxContentTypes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quota_MaxContentTypes");

                            b1.Property<int>("MaxSites")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quota_MaxSites");

                            b1.Property<long>("MaxStorageBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quota_MaxStorageBytes");

                            b1.Property<int>("MaxUsers")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quota_MaxUsers");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("MicroCMS.Domain.ValueObjects.TenantSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AiEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Settings_AiEnabled");

                            b1.Property<string>("DefaultLocale")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("TEXT")
                                .HasColumnName("Settings_DefaultLocale");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Settings_DisplayName");

                            b1.Property<string>("EnabledLocales")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("TEXT")
                                .HasColumnName("Settings_EnabledLocales");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT")
                                .HasColumnName("Settings_LogoUrl");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT")
                                .HasColumnName("Settings_TimeZoneId");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Quota")
                        .IsRequired();

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("MicroCMS.Domain.Aggregates.Webhooks.WebhookSubscription", b =>
                {
                    b.OwnsMany("MicroCMS.Domain.Aggregates.Webhooks.WebhookDeliveryLog", "DeliveryLogs", b1 =>
                        {
                            b1.Property<Guid>("WebhookSubscriptionId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("DeliveredAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("StatusCode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("WebhookSubscriptionId", "DeliveredAt");

                            b1.ToTable("WebhookDeliveryLogs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WebhookSubscriptionId");
                        });

                    b.Navigation("DeliveryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
